### ISSUE TITLE
How do you/should you debug in the notebook when teaching novices?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-bc#235]
This has come up several times (most recently in a comment on #233): what's the right way to debug a function that's broken (deliberately or otherwise) when teaching novices with the IPython Notebook?

1.  The authentic workflow is to go back and edit the cell over and over again until it's right, but that confuses learners (it doesn't leave a record of how you got the final answer).
2.  Clone/modify (successive refinement) leaves the trace, but unless you add Markdown or comments to explain what you're changing each time (which I never remember to do), the final notebook isn't very comprehensible either.
3.  The "right" solution is a breakpointing debugger, but we're not likely to have one in the notebook any time soon.

What else do people do, and how well does it work?

**Comment by bsmith89** [comment]
The IPython [`%debug` magic](https://ipython.org/ipython-doc/3/interactive/magics.html#magic-debug) works for me in IPython 4.1.2 (not sure when it was introduced).

If debugging is going to be a part of the lesson, this seems to be the easiest way to do it.
